//dependencies
const fs = require("fs");
const db = require("../db/db.json");

//api routes
module.exports = function (app) {
  //get returns db.json as a json
  app.get("/api/notes", function (req, res) {
    res.json(db);
  });
  // creates a new note, pushes new note to list of notes, writes new list to db.json
  app.post("/api/notes", function (req, res) {
    //new note contains id generated by uuid
    var newNote = {
      id: db.length,
      title: req.body.title,
      text: req.body.text,
    };
    db.push(newNote);
    // fs.writeFile("../db/db.json", JSON.stringify(db), (err) => {
    //   if (err) throw err;
    // });

    res.json(db);
  });

  app.delete("/api/notes:id", function (req, res) {
    const delID = req.params.id;
    console.log("params", req.params);
    console.log("id", req.params.id);
    db.splice(delID, 1);
    res.json(db);
  });


// //example routes because I'm getting an error trying to get elements from the dom :(
//     app.get("/api/test", function (req, res) {
//         res.json(db);
//       });    

// app.post("/api/test", function (req, res) {
//         //new note contains id generated by uuid
//         var newNote = {
//           id: db.length,
//           title: "New note posted!",
//           text: "Hi there",
//         };
//         db.push(newNote);
//         // fs.writeFile("../db/db.json", JSON.stringify(db), (err) => {
//         //   if (err) throw err;
//         // });
    
//         res.json(db);
//       });
    
//       app.delete("/api/delete:id", function (req, res) {
//         const delID = req.params.id;
//         console.log("params", req.params);
//         console.log("id", req.params.id);
//         db.splice(delID, 1);
//         res.json(db);
//       });

};
